-- Run this in the Supabase SQL Editor

-- Enable Vector Extension for embeddings
create extension if not exists vector;

-- 1. SIMULATIONS (The Universe Container)
-- Links a user to a specific instance of a Nomi
create table simulations (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_vibe jsonb, -- The extracted psychometric profile from the Oracle
  status text default 'ACTIVE' -- ACTIVE, ARCHIVED, PERMADEATH
);

-- 2. PERSONA_CORE (The Soul - Immutable)
-- Generated by the Foundry, defines the character's unchangeable traits
create table persona_core (
  id uuid default gen_random_uuid() primary key,
  simulation_id uuid references simulations(id) not null,
  
  -- Surface Layer
  name text not null,
  appearance text not null,
  voice_texture text not null,
  
  -- Deep Layer
  core_wound text not null,
  defense_mechanism text not null,
  attachment_style text not null,
  
  -- Value System (0-10 Scale stored as JSON)
  -- Example: {"silence": 9, "money": 2, "loyalty": 10}
  values_matrix jsonb not null, 
  
  -- Demographics
  sexual_orientation text not null,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. FLUID_STATES (The State Machine - Mutable)
-- Tracks the dynamic emotional state of the character
create table fluid_states (
  id uuid default gen_random_uuid() primary key,
  simulation_id uuid references simulations(id) not null,
  
  -- The Relationship Score (-100 to 100)
  emotional_bank_account int default 0,
  
  -- Dynamic needs
  current_craving text,
  
  -- Hidden variables (0-100)
  arousal_level int default 0,
  intellectual_boredom int default 0,
  
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. MEMORIES (Vector Store)
-- Stores episodic and semantic history
create table memories (
  id uuid default gen_random_uuid() primary key,
  simulation_id uuid references simulations(id) not null,
  content text not null,
  memory_type text not null, -- CORE, EPISODIC, SEMANTIC
  embedding vector(768), -- Prepared for Gemini text-embedding-004
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- This function allows us to search memories by semantic similarity
create or replace function match_memories (
  query_embedding vector(768),
  match_threshold float,
  match_count int,
  p_simulation_id uuid
)
returns table (
  id uuid,
  content text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    memories.id,
    memories.content,
    1 - (memories.embedding <=> query_embedding) as similarity
  from memories
  where 1 - (memories.embedding <=> query_embedding) > match_threshold
  and memories.simulation_id = p_simulation_id
  order by memories.embedding <=> query_embedding
  limit match_count;
end;
$$;
